# Be sure to restart your server when you modify this file.

# Version of your assets, change this if you want to expire all your assets.
Rails.application.config.assets.version = '1.0'

# Precompile additional assets.
# application.js, application.css, and all non-JS/CSS in app/assets folder are already added.
Rails.application.config.assets.precompile += %w( img/ico/favicon.ico
                                                  img/ico/apple-touch-icon.png
                                                  img/ico/apple-touch-icon-72.png
                                                  img/ico/apple-touch-icon-114.png
                                                  img/ico/apple-touch-icon-144.png
                                                  img/logo.png
                                                  img/slider/slider-bg-1.jpg
                                                  img/slider/responsive-iphone.png
                                                  img/slider/responsive-ipad.png
                                                  img/slider/responsive-imac.png
                                                  img/slider/slider-bg-2.jpg
                                                  img/iphone5c.png
                                                  img/portfolio/portfolio-1.jpg
                                                  img/portfolio/portfolio-2.jpg
                                                  img/portfolio/portfolio-3.jpg
                                                  img/portfolio/portfolio-4.jpg
                                                  img/portfolio/portfolio-5.jpg
                                                  img/portfolio/portfolio-6.jpg
                                                  img/clientslogo/logo-2.png
                                                  img/portfolio/portfolio-7.jpg
                                                  img/clientslogo/logo-1.png
                                                  img/clientslogo/logo-3.png
                                                  img/clientslogo/logo-4.png
                                                  img/clientslogo/logo-5.png
                                                  img/testimonial/team-member-1.jpg
                                                  img/testimonial/team-member-2.jpg
                                                  img/testimonial/team-member-3.jpg
                                                  css/bootstrap.css
                                                  css/bootstrap-theme.css
                                                  css/fonts/font-awesome/css/font-awesome.css
                                                  css/animations.css
                                                  css/superfish.css
                                                  css/revolution-slider/css/settings.css
                                                  css/prettyPhoto.css
                                                  css/style.css
                                                  css/global.css
                                                  css/colors/blue.css
                                                  css/theme-responsive.css
                                                  img/slider/slider-bg-11.jpg
                                                  img/bg_off.png
                                                  css/revolution-slider/assets/shadow1.png
                                                  css/revolution-slider/assets/shadow2.png
                                                  css/revolution-slider/assets/shadow3.png
                                                  css/revolution-slider/assets/boxed_bgtile.png
                                                  css/revolution-slider/assets/navigdots_bgtile.png
                                                  css/revolution-slider/assets/bullet.png
                                                  css/revolution-slider/assets/bullets.png
                                                  css/revolution-slider/assets/bullets2.png
                                                  css/revolution-slider/assets/bullet_boxed.png
                                                  css/revolution-slider/assets/navigdots.png
                                                  css/revolution-slider/assets/large_left.png
                                                  css/revolution-slider/assets/large_right.png
                                                  css/revolution-slider/assets/small_left.png
                                                  css/revolution-slider/assets/small_right.png
                                                  css/revolution-slider/assets/arrow_left.png
                                                  css/revolution-slider/assets/arrow_right.png
                                                  css/revolution-slider/assets/small_left_boxed.png
                                                  css/revolution-slider/assets/small_right_boxed.png
                                                  css/revolution-slider/assets/arrowleft.png
                                                  css/revolution-slider/assets/arrowright.png
                                                  css/revolution-slider/assets/arrow_left2.png
                                                  css/revolution-slider/assets/arrow_right2.png
                                                  css/revolution-slider/assets/timer.png
                                                  css/revolution-slider/assets/coloredbg.png
                                                  css/revolution-slider/assets/grain.png
                                                  css/revolution-slider/assets/loader.gif
                                                  css/revolution-slider/assets/loader2.gif
                                                  img/prettyPhoto/default/sprite.png
                                                  img/prettyPhoto/default/sprite_x.png
                                                  img/prettyPhoto/default/sprite_y.png
                                                  img/prettyPhoto/default/sprite_next.png
                                                  img/prettyPhoto/default/sprite_prev.png
                                                  img/prettyPhoto/default/default_thumb.png
                                                  img/prettyPhoto/default/loader.gif
                                                  img/prettyPhoto/light_rounded/sprite.png
                                                  img/prettyPhoto/light_rounded/btnNext.png
                                                  img/prettyPhoto/light_rounded/btnPrevious.png
                                                  img/prettyPhoto/light_rounded/loader.gif
                                                  img/prettyPhoto/light_rounded/default_thumbnail.gif
                                                  img/prettyPhoto/light_rounded/sprite.png
                                                  img/prettyPhoto/dark_rounded/sprite.png
                                                  img/prettyPhoto/dark_rounded/btnNext.png
                                                  img/prettyPhoto/dark_rounded/btnPrevious.png
                                                  img/prettyPhoto/dark_rounded/loader.gif
                                                  img/prettyPhoto/dark_rounded/default_thumbnail.gif
                                                  img/prettyPhoto/dark_rounded/contentPattern.png
                                                  img/prettyPhoto/dark_square/sprite.png
                                                  img/prettyPhoto/dark_square/btnNext.png
                                                  img/prettyPhoto/dark_square/btnPrevious.png
                                                  img/prettyPhoto/dark_square/loader.gif
                                                  img/prettyPhoto/dark_square/default_thumbnail.gif
                                                  img/prettyPhoto/dark_square/contentPattern.png
                                                  img/prettyPhoto/light_square/sprite.png
                                                  img/prettyPhoto/light_square/btnNext.png
                                                  img/prettyPhoto/light_square/btnPrevious.png
                                                  img/prettyPhoto/light_square/loader.gif
                                                  img/prettyPhoto/facebook/sprite.png
                                                  img/prettyPhoto/facebook/btnNext.png
                                                  img/prettyPhoto/facebook/btnPrevious.png
                                                  img/prettyPhoto/facebook/loader.gif
                                                  img/prettyPhoto/facebook/default_thumbnail.gif
                                                  img/prettyPhoto/facebook/contentPatternBottom.png
                                                  img/prettyPhoto/facebook/contentPatternLeft.png
                                                  img/prettyPhoto/facebook/contentPatternRight.png
                                                  img/prettyPhoto/facebook/contentPatternTop.png
                                                  img/ads-small.jpg
                                                  img/bg-black.png
                                                  img/bg_off.png
                                                  img/contact-map.png
                                                  img/fifo-small.jpg
                                                  img/glow.png
                                                  img/glyphicons-halflings-white.png
                                                  img/glyphicons-halflings.png
                                                  img/img-bg-blur.jpg
                                                  img/img-blur-lead.jpg
                                                  img/img-blur-lead2.jpg
                                                  img/pattern.png
                                                  img/placeholder-img.jpg
                                                  img/recent-post-img.jpg
                                                  img/search-icon.png
                                                  img/loader.gif )
